### PR TITLE
Fix #157: IO issues resulting from read.FCS w/ column.pattern

### LINKED ISSUE #157: Observables ignored in read.FCS still appear in @description, mess everything up when saving the file and reading it again
I am experiencing a strange behavior with `read.FCS()` in `flowCore_1.48.1`.
I have a FCS file which looks like the following:

```
> testfcs0 <- flowCore::read.FCS(InFiles[1])
> flowCore::pData(testfcs0@parameters) #INCLUDES $P5 - Center (and the rest)
             name            desc range   minRange maxRange
$P1       Bi209Di      209Bi_CD16 12000 -0.9999683    11999
$P2       Cd112Di      112Cd_CD14 12000 -0.9990196    11999
$P3       Cd114Di      114Cd_CD14 12000 -0.9996361    11999
$P4       Ce140Di     140Ce_gdTCR 12000 -0.9976195    11999
$P5        Center            <NA>  6166 -0.9397326     6165
$P6       Dy161Di      161Dy_TIM3   591 -0.9997892      590
$P7       Dy162Di     162Dy_CD161   867 -0.9991308      866
$P8       Dy163Di     163Dy_CD127   605 -0.9980708      604
$P9       Dy164Di     164Dy_ITGB7  1209 -0.9989309     1208
$P10      Er166Di     166Er_CXCR1  5315 -0.9998479     5314
$P11      Er167Di       167Er_APC  2034  0.0000000     2033
$P12      Er168Di      168Er_CCR7  1021 -0.9990532     1020
$P13      Er170Di       170Er_Vd2  2215 -0.9999682     2214
$P14      Eu151Di      151Eu_CD69 12000 -0.9886406    11999
$P15      Eu153Di     153Eu_KLRG1 12000 -0.9997312    11999
$P16 Event_length            <NA>   196  0.0000000      195
$P17      Gd155Di      155Gd_ICOS 12000 -1.0000000    11999
$P18      Gd156Di     156Gd_TIGIT 12000 -0.9999276    11999
...
```

Note here that the `maxRange` value for `Center` in `flowCore::pData(testfcs0@parameters)` is 6165.

I can retrieve this value from `testfcs0@description` as well:

```
> testfcs0@description$`$P5N`
[1] "Center"
> testfcs0@description$`flowCore_$P5Rmax`
[1] "6165"
```

Note as well that the `maxRange` value for `Dy161Di` (`$P6`) is 590.
```
> testfcs0@description$`$P6N`
[1] "Dy161Di"
> testfcs0@description$`flowCore_$P6Rmax`
[1] "590"
```

I want to ignore observables `Center`, `Event_length`, `Offset`, `Residual`, `SampleID`, `Time`. My real world case is a `flowSet` and some FCS files might contain those observables and some might not, so if I don't ignore them, errors will show.

So in this example I read my file in this way:

`testfcs <- flowCore::read.FCS(InFiles[1], column.pattern="Center|Event_length|Offset|Residual|SampleID|Time", invert.pattern=TRUE)`

Now `flowCore::pData(testfcs@parameters)` will look as follows:

```
> flowCore::pData(testfcs@parameters) #DOES NOT INCLUDE $P5 - Center (and the rest)
        name            desc range   minRange maxRange
$P1  Bi209Di      209Bi_CD16 12000 -0.9999683    11999
$P2  Cd112Di      112Cd_CD14 12000 -0.9990196    11999
$P3  Cd114Di      114Cd_CD14 12000 -0.9996361    11999
$P4  Ce140Di     140Ce_gdTCR 12000 -0.9976195    11999
$P6  Dy161Di      161Dy_TIM3   591 -0.9997892      590
$P7  Dy162Di     162Dy_CD161   867 -0.9991308      866
$P8  Dy163Di     163Dy_CD127   605 -0.9980708      604
$P9  Dy164Di     164Dy_ITGB7  1209 -0.9989309     1208
$P10 Er166Di     166Er_CXCR1  5315 -0.9998479     5314
$P11 Er167Di       167Er_APC  2034  0.0000000     2033
$P12 Er168Di      168Er_CCR7  1021 -0.9990532     1020
$P13 Er170Di       170Er_Vd2  2215 -0.9999682     2214
$P14 Eu151Di      151Eu_CD69 12000 -0.9886406    11999
$P15 Eu153Di     153Eu_KLRG1 12000 -0.9997312    11999
$P17 Gd155Di      155Gd_ICOS 12000 -1.0000000    11999
$P18 Gd156Di     156Gd_TIGIT 12000 -0.9999276    11999
...
```

Note there is no `$P5` (`Center`) anymore.

However, and here it's the problem, `$P5` (`Center`) still exists in `testfcs@description`.

```
> testfcs@description$`$P5N`
[1] "Center"
> testfcs@description$`flowCore_$P5Rmax`
[1] "6165"
```

If I now save my FCS file that I read without the above observables, and attempt to read it again, everything is messed up.

Reading in a FCS file, work on it adding extra information, and saving it for future reference is common procedure, so I don't think `flowCore` behavior here is appropriate...

See what happens.

I save the file I read without the above observables:

`flowCore::write.FCS(testfcs, "test.fcs")`

I read it in again:

`testfcs2 <- flowCore::read.FCS("test.fcs")`

Now `flowCore::pData(testfcs2@parameters)` has the observables renumbered (no numbers skipped like above), but `maxRange` values are retrieved from `testfcs2@description` (where ignored observables were not removed), so they do not correspond. A mess...

```
> flowCore::pData(testfcs2@parameters) #PARAMETERS ARE RENUMBERED, ALL maxRanges MESSED UP
        name            desc range   minRange maxRange
$P1  Bi209Di      209Bi_CD16 12000 -0.9999683    11999
$P2  Cd112Di      112Cd_CD14 12000 -0.9990196    11999
$P3  Cd114Di      114Cd_CD14 12000 -0.9996361    11999
$P4  Ce140Di     140Ce_gdTCR 12000 -0.9976195    11999
$P5  Dy161Di      161Dy_TIM3   591 -0.9997892     6165
$P6  Dy162Di     162Dy_CD161   867 -0.9991308      590
$P7  Dy163Di     163Dy_CD127   605 -0.9980708      866
$P8  Dy164Di     164Dy_ITGB7  1209 -0.9989309      604
$P9  Er166Di     166Er_CXCR1  5315 -0.9998479     1208
$P10 Er167Di       167Er_APC  2034  0.0000000     5314
$P11 Er168Di      168Er_CCR7  1021 -0.9990532     2033
$P12 Er170Di       170Er_Vd2  2215 -0.9999682     1020
$P13 Eu151Di      151Eu_CD69 12000 -0.9886406     2214
$P14 Eu153Di     153Eu_KLRG1 12000 -0.9997312    11999
$P15 Gd155Di      155Gd_ICOS 12000 -1.0000000    11999
$P16 Gd156Di     156Gd_TIGIT 12000 -0.9999276      195
$P17 Gd157Di     157Gd_CXCR3  1700 -0.9990172    11999
$P18 Gd158Di      158Gd_CD27  5886 -0.9999574    11999
...
```

Note now that `Dy161Di` is `$P5` instead of `$P6` now (fair enough).  But its `maxRange` value, as retrieved from `testfcs2@description`, is not 590 as it should be. Instead it is 6165 (the value for `Center`, the ignored observable).

From there on ALL the `maxRange` values are wrong, both in `flowCore::pData(testfcs2@parameters)` and in `testfcs2@description`

```
> testfcs2@description$`$P5N`
[1] "Dy161Di"
> testfcs2@description$`flowCore_$P5Rmax`
[1] "6165"

```

Please advice if I am doing something wrong, or this is something you can fix on your side. As of now I am spending a decent amount of time having to manually remove the ignored observables from `@description`, and manually renumbering `$Pn` both in `@parameters` and `@description` prior to saving my FCS file with `write.FCS()`...

Many thanks!

### PR DESCRIPTION
**Pull request by jacobpwagner**
@mikejiang , @gfinak , you can see the linked issue (#157)  for elaboration, but in short the issue is as follows. If `column.pattern` is used with `read.FCS`, the `description` will retain information for the omitted channels which will then carry forward if the `flowFrame` is subsequently passed to `write.FCS`. This will later cause issues if the resulting FCS is read in again as the indices will "bump down" to overlap with the indices of the previously omitted channels.

I'll call out the particularly problematic line in `write.FCS` in the diff below that results in the user's central issue.

There may also be better ways to handle this or changes that need to be made. Additionally, we may decide that it is not worth the potential ramifications of these changes, hence the PR.

### CODE REVIEW

File: R/IO.R [hunk 1]
```diff
@@ -1747,7 +1765,7 @@ write.FCS <- function(x, filename, what="numeric", delimiter = "|", endian = "bi
     
     #must clear the old $PnX before assigning the new ones since the old ones may not be dropped if fr was subsetted previously
     # because description<- only update or insert but does not delete the old
-    x@description <- orig.kw[!grepl("^\\$P[0-9]+[BERNS]$", names(orig.kw))]
+    x@description <- orig.kw[!grepl("\\$P[0-9]+[BERNS]", names(orig.kw))]
```
Comment (jacobpwagner) [inline R/IO.R]: This is the primarily offensive line, as in the prior form it will leave `flowCore_$PnRmax` key-value pairs in the description. This change causes those to be caught and removed along with any other `Pn` keys. Following the logic of the comment, these should be fully replaced due to potential subsetting (as in the issue).

**Comment by gfinak** [comment]
Looks like the unit test needs to be updated as a result.
`@test-IO.R#251`

**Comment by jacobpwagner** [comment]
Yep. I'm working through the tests now. Most are minor and expected changes, but one is more of an issue. By clipping out the `flowCore_$PnRmin/max` values in `write.FCS`, it causes an issue for the case of a transformed `flowFrame` being written out and read back in because if the `transformation` key has value `"custom"`, `read.FCS` will look for those `flowCore_$PnRmin/max` keys. So, we need to account for both the possibility of column subsetting and transformation. I could just explicitly bump down all `Pn` keys to fill the gaps at the time writing out. That logic could be added to `collapseDesc`.

**Comment by jacobpwagner** [comment]
This looks good now after d78cba5. No changes to tests are needed because now all of those keys are kept, but are now being assigned their proper values upon subset, solving the issue of #157. I will add some more tests to watch for this issue moving forward as well, but I'm going ahead with the merge.

File: R/IO.R (hunk 1 above)
Comment (jacobpwagner) [reply R/IO.R]: This line is removed in d78cba5
